# frozen_string_literal: true

require 'spec_helper'
require_relative '../sdk_compliance_adapter/adapter'

RSpec.describe ComplianceServer do
  let(:host) { 'http://127.0.0.1:19250' }
  let(:batches) { [] }

  def request(server, path, data = {})
    server.send(:route, 'POST', path, JSON.generate(data))
  end

  before do
    allow(TCPServer).to receive(:new).and_return(double('listener'))
    stub_request(:post, "#{host}/batch/").to_return do |req|
      body = req.headers['Content-Encoding'] == 'gzip' ? Zlib.gunzip(req.body) : req.body
      batches << JSON.parse(body)
      { status: 200, body: '{}' }
    end
  end

  after { SDKComplianceAdapter.state.reset }

  %w[async sync].each do |mode|
    context "with #{mode} capture" do
      let(:server) { described_class.new(mode: mode) }

      before do
        expect(request(server, '/init', api_key: 'test-key', host: host,
                                        flush_at: 100, flush_interval_ms: 60_000)).to eq([200, { success: true }])
      end

      it 'identifies the profile without changing SDK wire attribution' do
        expect(server.send(:health).last[:sdk_name]).to eq("posthog-ruby-#{mode}")
        request(server, '/capture', distinct_id: 'user', event: 'example')
        request(server, '/flush')
        expect(batches.first['batch'].first['properties']['$lib']).to eq('posthog-ruby')
      end

      it 'returns the UUID generated by the SDK and leaves transport timing to the mode' do
        expect(SDKComplianceAdapter.state.client).to receive(:capture).with(
          { distinct_id: 'user', event: 'example', properties: {} }
        ).and_call_original
        status, result = request(server, '/capture', distinct_id: 'user', event: 'example')
        expect(status).to eq(200)
        expect(result[:uuid]).to match(/\A[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}\z/)
        expect(batches.length).to eq(mode == 'sync' ? 1 : 0)
        request(server, '/flush')
        expect(batches.first['batch'].first['uuid']).to eq(result[:uuid])
        expect(SDKComplianceAdapter.state.snapshot).to include(total_events_captured: 1, pending_events: 0)
      end

      it 'generates distinct UUIDs across captures and forwards a supplied UUID unchanged' do
        results = 2.times.map { request(server, '/capture', distinct_id: 'user', event: 'example').last }
        uuid = '12345678-1234-4567-890a-123456789abc'
        results << request(server, '/capture', distinct_id: 'user', event: 'example', uuid: uuid).last
        request(server, '/flush')
        uuids = batches.flat_map { |batch| batch['batch'].map { |event| event['uuid'] } }
        expect(uuids).to eq(results.map { |result| result[:uuid] })
        expect(uuids.uniq.length).to eq(3)
        expect(uuids.last).to eq(uuid)
      end

      it 'passes a timestamp instant through the SDK UTC serializer' do
        request(server, '/capture', distinct_id: 'user', event: 'example', timestamp: '2024-01-02T03:04:05+05:30')
        request(server, '/flush')
        expect(batches.first['batch'].first['timestamp']).to eq('2024-01-01T21:34:05.000Z')
      end

      it 'honors disabled compression' do
        request(server, '/init', api_key: 'test-key', host: host, enable_compression: false)
        request(server, '/capture', distinct_id: 'user', event: 'example')
        request(server, '/flush')
        expect(a_request(:post, "#{host}/batch/").with do |req|
          !req.headers.key?('Content-Encoding')
        end).to have_been_made.once
      end

      it 'reports only events sent during each flush' do
        request(server, '/capture', distinct_id: 'user', event: 'example')
        expect(request(server, '/flush').last[:events_flushed]).to eq(mode == 'sync' ? 0 : 1)
        expect(request(server, '/flush').last[:events_flushed]).to eq(0)
      end

      [nil, false, true].each do |disable_geoip|
        it "preserves #{disable_geoip.inspect} GeoIP input through snapshot evaluation and real access capture" do
          flag_requests = []
          stub_request(:post, "#{host}/flags/?v=2").to_return do |req|
            flag_requests << JSON.parse(req.body)
            { status: 200, body: JSON.generate(featureFlags: { example: 'variant' }) }
          end
          data = { key: 'example', distinct_id: 'user' }
          data[:disable_geoip] = disable_geoip unless disable_geoip.nil?
          expect(request(server, '/get_feature_flag', data)).to eq([200, { success: true, value: 'variant' }])
          expect(flag_requests.first['flag_keys_to_evaluate']).to eq(['example'])
          if disable_geoip.nil?
            expect(flag_requests.first).not_to have_key('geoip_disable')
          else
            expect(flag_requests.first['geoip_disable']).to eq(disable_geoip)
          end
          expect(batches.flat_map { |batch| batch['batch'].map { |event| event['event'] } })
            .to eq(['$feature_flag_called'])
        end
      end
    end
  end

  it 'rejects an unknown profile' do
    expect { described_class.new(mode: 'unknown') }.to raise_error(ArgumentError, 'SDK_MODE must be async or sync')
  end
end
