# frozen_string_literal: true

require 'open3'
require 'tempfile'

module PublicApiSnapshot
  ROOT = File.expand_path('..', __dir__).freeze
  LIB_DIR = File.join(ROOT, 'lib').freeze
  SNAPSHOT_PATH = File.join(ROOT, 'public_api_snapshot.txt').freeze
  HEADER = <<~HEADER
    # This file is generated by `bundle exec rake public_api:generate`.
    # Run `bundle exec rake public_api:check` to detect local public API changes.
  HEADER

  module_function

  def generate
    load_sdk

    entries = []
    append_constant(entries, Object, :PostHog, 'PostHog')

    "#{HEADER}\n#{entries.join("\n")}\n"
  end

  def write
    File.write(SNAPSHOT_PATH, generate)
    puts "Updated #{relative_path(SNAPSHOT_PATH)}"
  end

  def check
    expected = File.exist?(SNAPSHOT_PATH) ? File.read(SNAPSHOT_PATH) : nil
    actual = generate

    return true if expected == actual

    warn 'Public API snapshot is out of date. Run `bundle exec rake public_api:generate` and review the diff.'
    print_diff(expected, actual)
    false
  end

  def load_sdk
    $LOAD_PATH.unshift(LIB_DIR) unless $LOAD_PATH.include?(LIB_DIR)
    require 'posthog'
  end

  def append_constant(entries, parent, constant_name, qualified_name)
    return if private_constant?(parent, constant_name, qualified_name)

    value = parent.const_get(constant_name, false)
    return unless value.is_a?(Module)

    entries << constant_entry(value, qualified_name)
    append_methods(entries, value, qualified_name)
    append_nested_constants(entries, value, qualified_name)
  end

  def append_nested_constants(entries, mod, qualified_name)
    mod.constants(false).sort_by(&:to_s).each do |constant_name|
      append_literal_constant(entries, mod, constant_name, qualified_name)
      append_constant(entries, mod, constant_name, "#{qualified_name}::#{constant_name}")
    end
  end

  def append_literal_constant(entries, mod, constant_name, qualified_name)
    return if private_constant?(mod, constant_name, "#{qualified_name}::#{constant_name}")

    value = mod.const_get(constant_name, false)
    return if value.is_a?(Module)

    entries << "constant #{qualified_name}::#{constant_name}: #{constant_type(value)}"
  end

  def append_methods(entries, mod, qualified_name)
    public_instance_methods(mod).each do |method_name|
      next if private_api_method?(mod.instance_method(method_name), method_name)

      entries << "instance_method #{qualified_name}##{method_name}#{method_signature(mod.instance_method(method_name))}"
    end

    public_singleton_methods(mod).each do |method_name|
      method = mod.method(method_name)
      next if private_api_method?(method, method_name)

      entries << "class_method #{qualified_name}.#{method_name}#{method_signature(method)}"
    end
  end

  def constant_entry(value, qualified_name)
    case value
    when Class
      superclass = value.superclass
      suffix = superclass && superclass != Object ? " < #{superclass.name}" : ''
      "class #{qualified_name}#{suffix}"
    else
      "module #{qualified_name}"
    end
  end

  def public_instance_methods(mod)
    mod.public_instance_methods(false).sort_by(&:to_s)
  end

  def public_singleton_methods(mod)
    mod.singleton_class.public_instance_methods(false).sort_by(&:to_s)
  end

  def private_constant?(parent, constant_name, qualified_name)
    qualified_name.start_with?('PostHog::Internal') ||
      source_marked_private?(parent.const_source_location(constant_name, false))
  end

  def private_api_method?(method, method_name)
    method_name.to_s.start_with?('_') || source_marked_private?(method.source_location)
  end

  def source_marked_private?(location)
    return false unless location

    file, line = location
    return false unless file&.start_with?(LIB_DIR) && File.file?(file)

    preceding_comment(file, line).include?('@api private')
  end

  def preceding_comment(file, line)
    lines = File.readlines(file)
    index = line - 2
    comment = []

    while index >= 0
      text = lines[index]
      break unless text.match?(/^\s*#/) || text.match?(/^\s*$/)

      comment.unshift(text)
      index -= 1
    end

    comment.join
  end

  def constant_type(value)
    return 'Boolean' if [true, false].include?(value)
    return 'nil' if value.nil?

    value.class.name
  end

  def method_signature(method)
    params = method.parameters.map.with_index do |(type, name), index|
      format_parameter(type, name, index)
    end
    "(#{params.join(', ')})"
  end

  def format_parameter(type, name, index)
    name ||= "arg#{index}"

    case type
    when :req
      name.to_s
    when :opt
      "#{name} = ..."
    when :rest
      "*#{name}"
    when :keyreq
      "#{name}:"
    when :key
      "#{name}: ..."
    when :keyrest
      "**#{name}"
    when :block
      "&#{name}"
    else
      "#{type}:#{name}"
    end
  end

  def print_diff(expected, actual)
    Tempfile.create('public-api-expected') do |expected_file|
      Tempfile.create('public-api-actual') do |actual_file|
        expected_file.write(expected || '')
        actual_file.write(actual)
        expected_file.flush
        actual_file.flush

        diff_output, stderr, status = Open3.capture3(
          'diff', '-u', '--label', relative_path(SNAPSHOT_PATH), expected_file.path,
          '--label', 'generated public API', actual_file.path
        )
        warn stderr unless stderr.empty?
        puts diff_output unless diff_output.empty?
        warn 'No diff output available.' unless status.exitstatus == 1 || !diff_output.empty?
      end
    end
  rescue Errno::ENOENT
    warn 'Install diff or run `bundle exec rake public_api:generate` to update the snapshot.'
  end

  def relative_path(path)
    path.delete_prefix("#{ROOT}/")
  end
end

if $PROGRAM_NAME == __FILE__
  case ARGV.first
  when '--check'
    exit(PublicApiSnapshot.check ? 0 : 1)
  when '--generate', nil
    PublicApiSnapshot.write
  else
    warn 'Usage: ruby scripts/public_api_snapshot.rb [--check|--generate]'
    exit 2
  end
end
